[project]
name = "survival_data_handler"
version = "2024.1.1"
description = ""
authors = [{ name = 'Vincent Laurent', email = 'vlaurent@eurobios.com' }]
readme = "README.md"


[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

